import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css'; // Import the FontAwesome styles
import Providers from '@/app/providers';
import { NextAppProvider } from '@toolpad/core/nextjs';
// import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
config.autoAddCss = false;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSansThai = Noto_Sans_Thai({
  subsets: ['thai', 'latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-toolpad-color-scheme="light" suppressHydrationWarning>
      {/* <body>
        <NextAppProvider
          navigation={NAVIGATION}
          branding={BRANDING}
          session={session}
          authentication={AUTHENTICATION}
          theme={theme}
        >
          {props.children}
        </NextAppProvider>
      </body> */}
      <body className={`${notoSansThai.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
